spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://sts.windows.net/095cf233-eca7-4e46-b9bf-8113574cb7ed/
          audience: api://80da648c-e621-43bd-b7ba-e4d2c0ea6a99